theme = "kanagawa_transparent"

[editor]
line-number = "relative"
color-modes = true
mouse = false
bufferline = "multiple"

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
j = { k = "normal_mode" }

