font:
  size: 12
  offset:
      x: 1
  # glyph_offset:
    # y: 9
  normal:
    family: "JetBrainsMonoNL Nerd Font Mono"
window:
  padding:
    x: 15
    y: 30
  # dimensions:
    #columns: 120
    #lines: 40
  opacity: 0.9
  decorations: buttonless

# Specifying '0' will disable timeout for blinking
  blink_timeout: 0

cursor:
  unfocused_hollow: true
  style:
    blinking: Always
# Cursor blinking interval in milliseconds.

  blink_interval: 750

env:
  TERM: xterm-256color

scrolling:
  history: 2000
  auto_scroll: true

#######################################
##      START OF COLOR SCHEMES       ##
#######################################
schemes:
  ### Doom One ###
  doom-one: &doom-one
    primary:
      background: '#282c34'
      foreground: '#bbc2cf'
    cursor:
      text: CellBackground
      cursor: '#528bff'
    selection:
      text: CellForeground
      background: '#3e4451'
    normal:
      black:   '#1c1f24'
      red:     '#ff6c6b'
      green:   '#98be65'
      yellow:  '#da8548'
      blue:    '#51afef'
      magenta: '#c678dd'
      cyan:    '#5699af'
      white:   '#f5f5f5'
    bright:
      black:   '#5b6268'
      red:     '#da8548'
      green:   '#4db5bd'
      yellow:  '#ecbe7b'
      blue:    '#3071db'   # This is 2257a0 in Doom Emacs but I lightened it.
      magenta: '#a9a1e1'
      cyan:    '#46d9ff'
      white:   '#f5f5f5'

  ### Doom Two ###
  doom-two: &doom-two
    primary:
      background: '#212121'
      foreground: '#f8f8f2'
    cursor:
      text: '0xfafafa'
      cursor: '0x41505e'
    selection:
      text: CellForeground
      background: '#3e4451'
    normal:
      black:   '#1c1f24'
      red:     '#ff6c6b'
      green:   '#98be65'
      yellow:  '#da8548'
      blue:    '#51afef'
      magenta: '#c678dd'
      cyan:    '#5699af'
      white:   '#f5f5f5'
    bright:
      black:   '#5b6268'
      red:     '#da8548'
      green:   '#4db5bd'
      yellow:  '#ecbe7b'
      blue:    '#3071db'   # This is 2257a0 in Doom Emacs but I lightened it.
      magenta: '#a9a1e1'
      cyan:    '#46d9ff'
      white:   '#f5f5f5'

  ### Dracula ###
  dracula: &dracula
    primary:
      background: '#282a36'
      foreground: '#f8f8f2'
    cursor:
      text: CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text: CellBackground
      cursor: CellForeground
    search:
      matches:
        foreground: '#44475a'
        background: '#50fa7b'
      focused_match:
        foreground: '#44475a'
        background: '#ffb86c'
      bar:
        background: '#282a36'
        foreground: '#f8f8f2'
    line_indicator:
      foreground: None
      background: None
    selection:
      text: CellForeground
      background: '#44475a'
    normal:
      black:   '#000000'
      red:     '#ff5555'
      green:   '#50fa7b'
      yellow:  '#f1fa8c'
      blue:    '#bd93f9'
      magenta: '#ff79c6'
      cyan:    '#8be9fd'
      white:   '#bfbfbf'
    bright:
      black:   '#4d4d4d'
      red:     '#ff6e67'
      green:   '#5af78e'
      yellow:  '#f4f99d'
      blue:    '#caa9fa'
      magenta: '#ff92d0'
      cyan:    '#9aedfe'
      white:   '#e6e6e6'
    dim:
      black:   '#14151b'
      red:     '#ff2222'
      green:   '#1ef956'
      yellow:  '#ebf85b'
      blue:    '#4d5b86'
      magenta: '#ff46b0'
      cyan:    '#59dffc'
      white:   '#e6e6d1'
  ### Dracula+ ###
  # Colors (Dracula+)
  dracula+: &dracula-plus
    bright:
      black: '#545454'
      blue: '#d6acff'
      cyan: '#a4ffff'
      green: '#69ff94'
      magenta: '#ff92df'
      red: '#ff6e6e'
      white: '#f8f8f2'
      yellow: '#ffcb6b'
    cursor:
      cursor: '#eceff4'
      text: '#282828'
    normal:
      black: '#21222c'
      blue: '#82aaff'
      cyan: '#8be9fd'
      green: '#50fa7b'
      magenta: '#c792ea'
      red: '#ff5555'
      white: '#f8f8f2'
      yellow: '#ffcb6b'
    primary:
      background: '#212121'
      foreground: '#f8f8f2'
    selection:
      background: '#f8f8f2'
      text: '#545454'

  ### Gruvbox dark ###
  gruvbox-dark: &gruvbox-dark
    # Default colors
    primary:
      # hard contrast: background = '0x1d2021'
      background: '#1b1b1b'
      # soft contrast: background = '0x32302f'
      foreground: '#ebdbb2'

    # Normal colors
    normal:
      black:   '#282828'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#a89984'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#fb4934'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

### Monokai ###
  monokai-pro: &monokai-pro
    # Default colors
    primary:
      background: '#2D2A2E'
      foreground: '#FCFCFA'

    # Normal colors
    normal:
      black:   '#403E41'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

    # Bright colors
    bright:
      black:   '#727072'
      red:     '#FF6188'
      green:   '#A9DC76'
      yellow:  '#FFD866'
      blue:    '#FC9867'
      magenta: '#AB9DF2'
      cyan:    '#78DCE8'
      white:   '#FCFCFA'

  ### Nord ###
  nord: &nord
    # Default colors
    primary:
      background: '#2E3440'
      foreground: '#D8DEE9'

    # Normal colors
    normal:
      black:   '#3B4252'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#88C0D0'
      white:   '#E5E9F0'

    # Bright colors
    bright:
      black:   '#4C566A'
      red:     '#BF616A'
      green:   '#A3BE8C'
      yellow:  '#EBCB8B'
      blue:    '#81A1C1'
      magenta: '#B48EAD'
      cyan:    '#8FBCBB'
      white:   '#ECEFF4'

  ### Oceanic Next ###
  oceanic-next: &oceanic-next
    # Default colors
    primary:
      background: '#1b2b34'
      foreground: '#d8dee9'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#1b2b34'
      cursor: '#ffffff'

    # Normal colors
    normal:
      black:   '#343d46'
      red:     '#EC5f67'
      green:   '#99C794'
      yellow:  '#FAC863'
      blue:    '#6699cc'
      magenta: '#c594c5'
      cyan:    '#5fb3b3'
      white:   '#d8dee9'

    # Bright colors
    bright:
      black:   '#343d46'
      red:     '#EC5f67'
      green:   '#99C794'
      yellow:  '#FAC863'
      blue:    '#6699cc'
      magenta: '#c594c5'
      cyan:    '#5fb3b3'
      white:   '#d8dee9'

  ### Solarized Light ###
  solarized-light: &solarized-light
    # Default colors
    primary:
      background: '#fdf6e3' # base3
      foreground: '#657b83' # base00

    # Cursor colors
    cursor:
      text:   '#fdf6e3' # base3
      cursor: '#657b83' # base00

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  ### Solarized Dark ###
  solarized-dark: &solarized-dark
    # Default colors
    primary:
      background: '#002b36' # base03
      foreground: '#839496' # base0

    # Cursor colors
    cursor:
      text:   '#002b36' # base03
      cursor: '#839496' # base0

    # Normal colors
    normal:
      black:   '#073642' # base02
      red:     '#dc322f' # red
      green:   '#859900' # green
      yellow:  '#b58900' # yellow
      blue:    '#268bd2' # blue
      magenta: '#d33682' # magenta
      cyan:    '#2aa198' # cyan
      white:   '#eee8d5' # base2

    # Bright colors
    bright:
      black:   '#002b36' # base03
      red:     '#cb4b16' # orange
      green:   '#586e75' # base01
      yellow:  '#657b83' # base00
      blue:    '#839496' # base0
      magenta: '#6c71c4' # violet
      cyan:    '#93a1a1' # base1
      white:   '#fdf6e3' # base3

  ### Tomorrow Night ###
  tomorrow-night: &tomorrow-night
     # Default colors
    primary:
      background: '#1d1f21'
      foreground: '#c5c8c6'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#1d1f21'
      cursor: '#ffffff'

    # Normal colors
    normal:
      black:   '#1d1f21'
      red:     '#cc6666'
      green:   '#b5bd68'
      yellow:  '#e6c547'
      blue:    '#81a2be'
      magenta: '#b294bb'
      cyan:    '#70c0ba'
      white:   '#373b41'

    # Bright colors
    bright:
      black:   '#666666'
      red:     '#ff3334'
      green:   '#9ec400'
      yellow:  '#f0c674'
      blue:    '#81a2be'
      magenta: '#b77ee0'
      cyan:    '#54ced6'
      white:   '#282a2e'

  ### moonfly ###
  moonfly: &moonfly
     # Default colors
    primary:
      background: '#080808'
      foreground: '#b2b2b2'

    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '#080808'
      cursor: '#b2b2b2'

    # Normal colors
    normal:
      black:   '#323437'
      red:     '#ff5454'
      green:   '#8cc85f'
      yellow:  '#e3c78a'
      blue:    '#80a0ff'
      magenta: '#d183e8'
      cyan:    '#79dac8'
      white:   '#c6c6c6'

    # Bright colors
    bright:
      black:   '#949494'
      red:     '#ff5189'
      green:   '#36c692'
      yellow:  '#bfbf97'
      blue:    '#74b2ff'
      magenta: '#ae81ff'
      cyan:    '#85dc85'
      white:   '#e4e4e4'

# Colors (PaperColor - Light)

  ### papercolor ###
  papercolor: &papercolor

  # Default colors
    primary:
      background: '0xeeeeee'
      foreground: '0x878787'

    cursor:
      text: '0xeeeeee'
      cursor: '0x878787'

  # Normal colors
    normal:
      black:   '0xeeeeee'
      red:     '0xaf0000'
      green:   '0x008700'
      yellow:  '0x5f8700'
      blue:    '0x0087af'
      magenta: '0x878787'
      cyan:    '0x005f87'
      white:   '0x444444'

  # Bright colors
    bright:
      black:   '0xbcbcbc'
      red:     '0xd70000'
      green:   '0xd70087'
      yellow:  '0x8700af'
      blue:    '0xd75f00'
      magenta: '0xd75f00'
      cyan:    '0x005faf'
      white:   '0x005f87'

  ### city lights ###
  city-lights: &city-lights
  
  # Default colors
    primary:
      background: '0x171d23'
      foreground: '0xffffff'

    # Cursor colors
    cursor:
      text:   '0xfafafa'
      cursor: '0x41505e'

    # Normal colors
    normal:
      black:   '0x333f4a'
      red:     '0xd95468'
      green:   '0x8bd49c'
      blue:    '0x539afc'
      magenta: '0xb62d65'
      cyan:    '0x70e1e8'
      white:   '0xb7c5d3'

    # Bright colors
    bright:
      black:   '0x41505e'
      red:     '0xd95468'
      green:   '0x8bd49c'
      yellow:  '0xebbf83'
      blue:    '0x5ec4ff'
      magenta: '0xe27e8d'
      cyan:    '0x70e1e8'
      white:   '0xffffff'


    ### hex_steel ###
  hex_steel: &hex_steel

     # Default colors
     primary:
       background: '0x0e0e0d'
       foreground: '0xffffff'
   
     # Cursor colors
     cursor:
       text: '0xfafafa'
       cursor: '0x41505e'
   
     # Normal colors
     normal:
       black: '0x333f4a'
       red: '0xd95468'
       green: '0x8bd49c'
       yellow: '0x539afc'
       blue: '0xb62d65'
       magenta: '0x70e1e8'
       cyan: '0xb7c5d3'
       white: '0x656869'
   
     # Bright colors
     bright:
       black: '0x41505e'
       red: '0xd95468'
       green: '0x8bd49c'
       yellow: '0xebbf83'
       blue: '0x5ec4ff'
       magenta: '0xe27e8d'
       cyan: '0x70e1e8'
       white: '0xffffff'
   
    # Colors (kanagawa)
  kanagawa: &kanagawa

   primary:
     background: '0x1f1f28'
     foreground: '0xdcd7ba'
   
   normal:
     black:   '0x090618'
     red:     '0xc34043'
     green:   '0x76946a'
     yellow:  '0xc0a36e'
     blue:    '0x7e9cd8'
     magenta: '0x957fb8'
     cyan:    '0x6a9589'
     white:   '0xc8c093'
   
   bright:
     black:   '0x727169'
     red:     '0xe82424'
     green:   '0x98bb6c'
     yellow:  '0xe6c384'
     blue:    '0x7fb4ca'
     magenta: '0x938aa9'
     cyan:    '0x7aa89f'
     white:   '0xdcd7ba'
   
   selection:
     background: '0x2d4f67'
     foreground: '0xc8c093'
   
   indexed_colors:
     - { index: 16, color: '0xffa066' }
     - { index: 17, color: '0xff5d62' }

######################################################################
## SET THEME: Choose ONE color scheme from those in the above list. ##
## ###################################################################
# Available themes are:
# *doom-one
# *dracula-plus
# *dracula
# *gruvbox-dark
# *monokai-pro
# *nord
# *oceanic-next
# *solarized-light
# *solarized-dark
# *tomorrow-night
# *city-lights
# *hex_steel

colors: *kanagawa

#######################################
##       END OF COLOR SCHEMES        ##
#######################################
