#!/bin/zsh

function find_git_repositories() {
  local dir="$1"
  local depth="$2"

  if [[ -L "$dir" ]]; then
    return
  fi

  if [[ -d "$dir/.git" ]]; then
    # Print the Git URL and the current directory
    url=$(git -C "$dir" config --get remote.origin.url)
    echo "Git URL: $url"
    echo "Current Directory: $dir"
    echo
  fi

  if [[ $depth -gt 0 ]]; then
    for item in "$dir"/*; do
      if [[ -d "$item" ]]; then
        find_git_repositories "$item" $((depth - 1))
      fi
    done
  fi
}

# Start searching from the specified directory (e.g., the root of your dotfiles)
find_git_repositories "$PWD" 10
