# Aliases

alias orca="~/Orca-c/build/orca"
alias brave="open -a Brave\ Browser"
alias vscode="open -a Visual\ Studio\ Code"
alias jn="jupyter notebook"
alias jl="jupyter lab"
alias whatsapp="open -a WhatsApp"
alias max="open -a Max"
alias discord="open -a Discord"
alias slack="open -a Slack"
alias subl="open -a Sublime\ Text"
alias ls="exa --icons -1 -G"
alias .="cd ../"
alias ..="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias .....="cd ../../../../.."
alias c="clear"
alias e="exit"
alias bat="cat"
alias base="conda activate base"
